spring:

  datasource:
    url: jdbc:mysql://localhost:3306/dmtbs?useSSL=false&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  session:
    store-type: jdbc
    jdbc:
      schema: mysql

